// Generate computed/ artifacts: relationship graph (JSON + deterministic HTML),
// capability matrix (ladder rungs, never bare checkmarks), complementarity pairs.
// Everything here is interpretation, stored apart from declared records, stamped.
import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadRegistry, stamp, ROOT, type Doc } from "./registry-load.js";
import { pairs, WEIGHTS, ALGORITHM_VERSION } from "./complementarity.js";

const DOMAINS = ["identity", "authority", "context", "environment", "policy",
  "decision", "receipt", "repair", "observer", "provenance"];
const LADDER = ["CLAIMS_TO_IMPLEMENT", "MANIFEST_VALIDATED", "REFERENCE_IMPLEMENTATION", "CONFORMANCE_TESTED"];

export function buildAll() {
  const { projects, edges, inputs } = loadRegistry();
  const summary = {
    registered: projects.filter((p) => p.project.record_state === "registered").length,
    observed: projects.filter((p) => p.project.record_state === "observed").length,
    example: projects.filter((p) => p.project.record_state === "example").length,
  };

  const graph = {
    stamp: stamp("graph-0.1.0", {}, inputs),
    summary,
    nodes: projects.map((p) => ({
      id: p.project.id, name: p.project.name,
      record_state: p.project.record_state, status: p.project.status,
    })),
    edges: edges.map((e) => ({
      source: e.source_project, target: e.target_project,
      type: e.relationship_type, status: e.status,
    })),
  };

  // v0.1 rung logic: records here have already passed `npm run validate`
  // (schema + semantic rules) → MANIFEST_VALIDATED. REFERENCE_IMPLEMENTATION and
  // CONFORMANCE_TESTED are defined but unpopulated — no proposal has recorded a
  // reference, and no conformance suite exists yet. Stating that is the honesty.
  const matrix = {
    stamp: stamp("matrix-0.1.0", { rung_logic: "validated-manifest-v0.1" }, inputs),
    ladder: LADDER,
    unpopulated_rungs: ["REFERENCE_IMPLEMENTATION", "CONFORMANCE_TESTED"],
    summary,
    rows: projects.map((p) => ({
      id: p.project.id,
      record_state: p.project.record_state,
      provides: Object.fromEntries(DOMAINS
        .filter((d) => (p.interfaces?.provides ?? []).includes(d))
        .map((d) => [d, "MANIFEST_VALIDATED"])),
      consumes: (p.interfaces?.consumes ?? []).filter((d: string) => DOMAINS.includes(d)),
    })),
  };

  const comp = {
    stamp: stamp(ALGORITHM_VERSION, WEIGHTS as unknown as Doc, inputs),
    summary,
    pairs: pairs(projects, edges),
  };
  return { graph, matrix, comp };
}

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
export function graphHtml(graph: ReturnType<typeof buildAll>["graph"]): string {
  const rows = graph.edges.map((e) =>
    `<tr><td>${esc(e.source)}</td><td>${esc(e.type)}</td><td>${esc(e.target)}</td><td>${esc(e.status)}</td></tr>`).join("\n");
  const nodes = graph.nodes.map((n) =>
    `<li>${esc(n.id)} — ${esc(n.name)} <em>(${esc(n.record_state)}, ${esc(n.status)})</em></li>`).join("\n");
  return `<!-- generated by graph-0.1.0; computed interpretation, not authoritative -->
<h1>OTCS relationship graph</h1>
<p>${graph.summary.registered} registered · ${graph.summary.observed} observed · ${graph.summary.example} example (excluded from real counts)</p>
<ul>\n${nodes}\n</ul>
<table><tr><th>source</th><th>relationship</th><th>target</th><th>status</th></tr>\n${rows}\n</table>`;
}

// ---- CLI -------------------------------------------------------------------
if (process.argv[1]?.endsWith("generate.ts")) {
  // Regeneration is idempotent by default. `generated_at` is the only field in a
  // computed artifact that is not derived from its inputs, so it is inherited from
  // the committed artifact rather than taken from the clock — otherwise `npm run
  // generate` rewrites it and the golden-file test fails on a change nobody made.
  // A release sets OTCS_BUILD_TIME explicitly to mark a genuinely new build.
  const prior = join(ROOT, "computed", "graph.json");
  if (!process.env.OTCS_BUILD_TIME && existsSync(prior)) {
    process.env.OTCS_BUILD_TIME = JSON.parse(readFileSync(prior, "utf8")).stamp.generated_at;
    console.log(`inherited build time ${process.env.OTCS_BUILD_TIME} (set OTCS_BUILD_TIME to mark a new build)`);
  }
  const { graph, matrix, comp } = buildAll();
  const out = join(ROOT, "computed");
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, "graph.json"), JSON.stringify(graph, null, 2) + "\n");
  writeFileSync(join(out, "graph.html"), graphHtml(graph) + "\n");
  writeFileSync(join(out, "matrix.json"), JSON.stringify(matrix, null, 2) + "\n");
  writeFileSync(join(out, "complementarity.json"), JSON.stringify(comp, null, 2) + "\n");
  console.log(`computed/: graph.json graph.html matrix.json complementarity.json (${graph.nodes.length} records, ${graph.edges.length} edges)`);
}
